### ISSUE TITLE
Add TLX device type for Growatt

### ISSUE THREAD

**Issue by dannyphamm** [danwale/SolarUseOptimiser#2]
**Is your feature request related to a problem? Please describe.**
First time using it. it didn't work saying asks for a MIN or INV device type but my device type is a "TLX". Looking at the code it has pac and etotal so I'm assuming it is the same as INV

Sample

```
"datas": [
	    {
		"deviceType": "0",
		"ptoStatus": "0",
		"timeServer": "",
		"accountName": "",
		"timezone": "11",
		"plantId": "",
		"deviceTypeName": "tlx",
		"nominalPower": "5000",
		"bdcStatus": "0",
		"eToday": "7.1",
		"eMonth": "167.8",
		"datalogTypeTest": "ShineWiFi-X",
		"eTotal": "4442.6",
		"pac": "3343.9",
		"datalogSn": "",
		"alias": "",
		"location": "",
		"deviceModel": "MIN 5000TL-X",
		"sn": "",
		"plantName": "Home",
		"status": "1",
		"lastUpdateTime": "2023-05-15 12:49:34"
}
],
````
**Describe the solution you'd like**
Add TLX device type in Growatt. Where INV is as well

**Describe alternatives you've considered**
None. I believe it can be done the same as INV

**Additional context**
I pulled the repo and added some code, and it seems to work. Can create a pull request :)

**Comment by danwale** [comment]
Hi I've made the change and it'll push the new version as soon as the pipelines complete, thanks for the feedback. It'll be version 1.0.11 (and replace the latest tag).

**Comment by dannyphamm** [comment]
Connected. Thanks Daniel!
